#!/bin/bash
export PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin

adb connect

service ssh restart

killall -9 ruby
killall -9 ngrok

cd /home/ppibburr/remixos-input/bin
ruby /home/ppibburr/remixos-input/bin/remixos-input eth0 -o 0.0.0.0 touch
