#!/bin/bash
export PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin

adb connect

service ssh restart


killall -9 ngrok

rm /home/ppibburr/remixos-input/bin/log.txt

bash /home/ppibburr/remixos-input/scripts/start.sh
